version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: postgres-dev
      POSTGRES_PASSWORD: s3cr3tp4ssw0rd
    ports:
        - 5432:5432
  app:
    environment:
      HOST: db
      DB: dev
      USER: postgres-dev
      PASSWORD: s3cr3tp4ssw0rd
    build: .
    command: ["./wait-for-it.sh", "db:5432", "--", "go", "run", "main.go"]
    volumes:
        - .:/go/src/app
    ports:
        - "8080:8000"
    depends_on:
        - db
    links:
        - db
